services:

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      SLM_HOST: ${SLM_HOST}
    ports:
      - "8000:8000"
    depends_on:
      - database
      - slm
    volumes:
      - ./backend:/app # hot reloading

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
    - ./frontend:/app
    - /app/node_modules
    depends_on:
      - backend

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  slm:
    build: ./ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11435:11434"
    tty: true
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data: