services:

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
    ports:
      - "8000:8000"
    depends_on:
      - database
      - slm
    volumes:
      - ./backend:/app # hot reloading

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  slm:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    tty: true
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data: